// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CMF_teste_array_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CMF_teste_array_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CMF_teste_array_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> CMF_teste_array_2::ap_ST_fsm_state1 = "1";
const sc_lv<2> CMF_teste_array_2::ap_ST_fsm_state2 = "10";
const sc_lv<32> CMF_teste_array_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> CMF_teste_array_2::ap_const_lv1_0 = "0";
const sc_lv<15> CMF_teste_array_2::ap_const_lv15_0 = "000000000000000";
const sc_lv<1> CMF_teste_array_2::ap_const_lv1_1 = "1";
const sc_lv<32> CMF_teste_array_2::ap_const_lv32_1 = "1";
const sc_lv<32> CMF_teste_array_2::ap_const_lv32_2 = "10";
const sc_lv<32> CMF_teste_array_2::ap_const_lv32_E = "1110";
const sc_lv<13> CMF_teste_array_2::ap_const_lv13_1 = "1";
const sc_lv<15> CMF_teste_array_2::ap_const_lv15_1 = "1";
const bool CMF_teste_array_2::ap_const_boolean_1 = true;

CMF_teste_array_2::CMF_teste_array_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dados1_U = new CMF_teste_array_2bkb("dados1_U");
    dados1_U->clk(ap_clk);
    dados1_U->reset(ap_rst);
    dados1_U->address0(dados1_address0);
    dados1_U->ce0(dados1_ce0);
    dados1_U->q0(dados1_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Saida);
    sensitive << ( dados1_q0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Saida_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_tmp_6_phi_fu_63_p4);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( k );
    sensitive << ( storemerge_fu_112_p3 );
    sensitive << ( tmp_fu_73_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dados1_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_7_fu_127_p1 );

    SC_METHOD(thread_dados1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_icmp_fu_100_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_73_p2 );
    sensitive << ( tmp_1_fu_90_p4 );

    SC_METHOD(thread_storemerge_fu_112_p3);
    sensitive << ( icmp_fu_100_p2 );
    sensitive << ( tmp_3_fu_106_p2 );

    SC_METHOD(thread_tmp_1_fu_90_p4);
    sensitive << ( k );

    SC_METHOD(thread_tmp_3_fu_106_p2);
    sensitive << ( k );

    SC_METHOD(thread_tmp_7_fu_127_p1);
    sensitive << ( ap_phi_mux_tmp_6_phi_fu_63_p4 );

    SC_METHOD(thread_tmp_fu_73_p2);
    sensitive << ( pulsoSinc );
    sensitive << ( SimCLK );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    SimCLK = "0";
    k = "000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CMF_teste_array_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, pulsoSinc, "(port)pulsoSinc");
    sc_trace(mVcdFile, Saida, "(port)Saida");
    sc_trace(mVcdFile, Saida_ap_vld, "(port)Saida_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, SimCLK, "SimCLK");
    sc_trace(mVcdFile, k, "k");
    sc_trace(mVcdFile, dados1_address0, "dados1_address0");
    sc_trace(mVcdFile, dados1_ce0, "dados1_ce0");
    sc_trace(mVcdFile, dados1_q0, "dados1_q0");
    sc_trace(mVcdFile, storemerge_fu_112_p3, "storemerge_fu_112_p3");
    sc_trace(mVcdFile, ap_phi_mux_tmp_6_phi_fu_63_p4, "ap_phi_mux_tmp_6_phi_fu_63_p4");
    sc_trace(mVcdFile, tmp_fu_73_p2, "tmp_fu_73_p2");
    sc_trace(mVcdFile, tmp_7_fu_127_p1, "tmp_7_fu_127_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_1_fu_90_p4, "tmp_1_fu_90_p4");
    sc_trace(mVcdFile, icmp_fu_100_p2, "icmp_fu_100_p2");
    sc_trace(mVcdFile, tmp_3_fu_106_p2, "tmp_3_fu_106_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("CMF_teste_array_2.hdltvin.dat");
    mHdltvoutHandle.open("CMF_teste_array_2.hdltvout.dat");
}

CMF_teste_array_2::~CMF_teste_array_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete dados1_U;
}

void CMF_teste_array_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_fu_73_p2.read(), ap_const_lv1_1))) {
        SimCLK = pulsoSinc.read();
        k = storemerge_fu_112_p3.read();
    }
}

void CMF_teste_array_2::thread_Saida() {
    Saida = esl_zext<15,6>(dados1_q0.read());
}

void CMF_teste_array_2::thread_Saida_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Saida_ap_vld = ap_const_logic_1;
    } else {
        Saida_ap_vld = ap_const_logic_0;
    }
}

void CMF_teste_array_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CMF_teste_array_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void CMF_teste_array_2::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void CMF_teste_array_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CMF_teste_array_2::thread_ap_phi_mux_tmp_6_phi_fu_63_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_73_p2.read())) {
            ap_phi_mux_tmp_6_phi_fu_63_p4 = k.read();
        } else if (esl_seteq<1,1,1>(tmp_fu_73_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_tmp_6_phi_fu_63_p4 = storemerge_fu_112_p3.read();
        } else {
            ap_phi_mux_tmp_6_phi_fu_63_p4 = "XXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_tmp_6_phi_fu_63_p4 = "XXXXXXXXXXXXXXX";
    }
}

void CMF_teste_array_2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void CMF_teste_array_2::thread_dados1_address0() {
    dados1_address0 =  (sc_lv<3>) (tmp_7_fu_127_p1.read());
}

void CMF_teste_array_2::thread_dados1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dados1_ce0 = ap_const_logic_1;
    } else {
        dados1_ce0 = ap_const_logic_0;
    }
}

void CMF_teste_array_2::thread_icmp_fu_100_p2() {
    icmp_fu_100_p2 = (!tmp_1_fu_90_p4.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<1>(): (sc_bigint<13>(tmp_1_fu_90_p4.read()) < sc_bigint<13>(ap_const_lv13_1));
}

void CMF_teste_array_2::thread_storemerge_fu_112_p3() {
    storemerge_fu_112_p3 = (!icmp_fu_100_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_fu_100_p2.read()[0].to_bool())? tmp_3_fu_106_p2.read(): ap_const_lv15_0);
}

void CMF_teste_array_2::thread_tmp_1_fu_90_p4() {
    tmp_1_fu_90_p4 = k.read().range(14, 2);
}

void CMF_teste_array_2::thread_tmp_3_fu_106_p2() {
    tmp_3_fu_106_p2 = (!k.read().is_01() || !ap_const_lv15_1.is_01())? sc_lv<15>(): (sc_biguint<15>(k.read()) + sc_biguint<15>(ap_const_lv15_1));
}

void CMF_teste_array_2::thread_tmp_7_fu_127_p1() {
    tmp_7_fu_127_p1 = esl_zext<64,15>(ap_phi_mux_tmp_6_phi_fu_63_p4.read());
}

void CMF_teste_array_2::thread_tmp_fu_73_p2() {
    tmp_fu_73_p2 = (SimCLK.read() ^ pulsoSinc.read());
}

void CMF_teste_array_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void CMF_teste_array_2::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pulsoSinc\" :  \"" << pulsoSinc.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida\" :  \"" << Saida.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida_ap_vld\" :  \"" << Saida_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

