// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _CMFfixedop_HH_
#define _CMFfixedop_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "CMFfixedop_mul_mubkb.h"

namespace ap_rtl {

struct CMFfixedop : public sc_module {
    // Port declarations 10
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<18> > Entrada1_V;
    sc_in< sc_lv<18> > Entrada2_V;
    sc_out< sc_lv<18> > Saida1_V;
    sc_out< sc_logic > Saida1_V_ap_vld;
    sc_out< sc_lv<18> > Saida2_V;
    sc_out< sc_logic > Saida2_V_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    CMFfixedop(sc_module_name name);
    SC_HAS_PROCESS(CMFfixedop);

    ~CMFfixedop();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    CMFfixedop_mul_mubkb<1,1,18,18,30>* CMFfixedop_mul_mubkb_U1;
    sc_signal< sc_lv<18> > addconv_fu_50_p0;
    sc_signal< sc_lv<18> > addconv_fu_50_p1;
    sc_signal< sc_lv<30> > r_V_fu_75_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_1D;
    // Thread declarations
    void thread_Saida1_V();
    void thread_Saida1_V_ap_vld();
    void thread_Saida2_V();
    void thread_Saida2_V_ap_vld();
    void thread_addconv_fu_50_p0();
    void thread_addconv_fu_50_p1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
