// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CMFfixedop,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.180000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=0,HLS_SYN_LUT=25,HLS_VERSION=2018_3}" *)

module CMFfixedop (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Entrada1_V,
        Entrada2_V,
        Saida1_V,
        Saida1_V_ap_vld,
        Saida2_V,
        Saida2_V_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] Entrada1_V;
input  [17:0] Entrada2_V;
output  [17:0] Saida1_V;
output   Saida1_V_ap_vld;
output  [17:0] Saida2_V;
output   Saida2_V_ap_vld;

reg Saida1_V_ap_vld;
reg Saida2_V_ap_vld;

wire  signed [17:0] addconv_fu_50_p0;
wire  signed [17:0] addconv_fu_50_p1;
wire  signed [29:0] r_V_fu_75_p2;

CMFfixedop_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
CMFfixedop_mul_mubkb_U1(
    .din0(Entrada2_V),
    .din1(Entrada1_V),
    .dout(r_V_fu_75_p2)
);

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        Saida1_V_ap_vld = 1'b1;
    end else begin
        Saida1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        Saida2_V_ap_vld = 1'b1;
    end else begin
        Saida2_V_ap_vld = 1'b0;
    end
end

assign Saida1_V = ($signed(addconv_fu_50_p0) + $signed(addconv_fu_50_p1));

assign Saida2_V = {{r_V_fu_75_p2[29:12]}};

assign addconv_fu_50_p0 = Entrada2_V;

assign addconv_fu_50_p1 = Entrada1_V;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

endmodule //CMFfixedop
