// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CMF_testa_array.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CMF_testa_array::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CMF_testa_array::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> CMF_testa_array::ap_ST_fsm_state1 = "1";
const sc_lv<32> CMF_testa_array::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> CMF_testa_array::ap_const_lv32_2 = "10";
const sc_lv<32> CMF_testa_array::ap_const_lv32_1F = "11111";
const sc_lv<30> CMF_testa_array::ap_const_lv30_1 = "1";
const sc_lv<32> CMF_testa_array::ap_const_lv32_1 = "1";
const sc_lv<32> CMF_testa_array::ap_const_lv32_1E = "11110";
const sc_lv<32> CMF_testa_array::ap_const_lv32_28 = "101000";
const bool CMF_testa_array::ap_const_boolean_1 = true;

CMF_testa_array::CMF_testa_array(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_fu_38_p2 );

    SC_METHOD(thread_icmp_fu_38_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_28_p4 );

    SC_METHOD(thread_storemerge_fu_50_p3);
    sensitive << ( icmp_fu_38_p2 );
    sensitive << ( tmp_2_fu_44_p2 );

    SC_METHOD(thread_tmp_2_fu_44_p2);
    sensitive << ( k );

    SC_METHOD(thread_tmp_fu_28_p4);
    sensitive << ( k );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    k = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CMF_testa_array_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, k, "k");
    sc_trace(mVcdFile, storemerge_fu_50_p3, "storemerge_fu_50_p3");
    sc_trace(mVcdFile, tmp_fu_28_p4, "tmp_fu_28_p4");
    sc_trace(mVcdFile, icmp_fu_38_p2, "icmp_fu_38_p2");
    sc_trace(mVcdFile, tmp_2_fu_44_p2, "tmp_2_fu_44_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("CMF_testa_array.hdltvin.dat");
    mHdltvoutHandle.open("CMF_testa_array.hdltvout.dat");
}

CMF_testa_array::~CMF_testa_array() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void CMF_testa_array::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k = storemerge_fu_50_p3.read();
    }
}

void CMF_testa_array::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CMF_testa_array::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void CMF_testa_array::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CMF_testa_array::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void CMF_testa_array::thread_ap_return() {
    ap_return = (!icmp_fu_38_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_fu_38_p2.read()[0].to_bool())? ap_const_lv32_1E: ap_const_lv32_28);
}

void CMF_testa_array::thread_icmp_fu_38_p2() {
    icmp_fu_38_p2 = (!tmp_fu_28_p4.read().is_01() || !ap_const_lv30_1.is_01())? sc_lv<1>(): (sc_bigint<30>(tmp_fu_28_p4.read()) < sc_bigint<30>(ap_const_lv30_1));
}

void CMF_testa_array::thread_storemerge_fu_50_p3() {
    storemerge_fu_50_p3 = (!icmp_fu_38_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_fu_38_p2.read()[0].to_bool())? tmp_2_fu_44_p2.read(): ap_const_lv32_0);
}

void CMF_testa_array::thread_tmp_2_fu_44_p2() {
    tmp_2_fu_44_p2 = (!k.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void CMF_testa_array::thread_tmp_fu_28_p4() {
    tmp_fu_28_p4 = k.read().range(31, 2);
}

void CMF_testa_array::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void CMF_testa_array::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

