// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CMF_duas_saidas.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CMF_duas_saidas::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CMF_duas_saidas::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> CMF_duas_saidas::ap_const_lv32_1 = "1";
const sc_lv<32> CMF_duas_saidas::ap_const_lv32_2 = "10";
const bool CMF_duas_saidas::ap_const_boolean_1 = true;

CMF_duas_saidas::CMF_duas_saidas(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_Saida1);
    sensitive << ( ap_start );
    sensitive << ( Entrada );

    SC_METHOD(thread_Saida1_ap_vld);
    sensitive << ( ap_start );

    SC_METHOD(thread_Saida2);
    sensitive << ( ap_start );
    sensitive << ( Entrada );

    SC_METHOD(thread_Saida2_ap_vld);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CMF_duas_saidas_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Saida1, "(port)Saida1");
    sc_trace(mVcdFile, Saida1_ap_vld, "(port)Saida1_ap_vld");
    sc_trace(mVcdFile, Saida2, "(port)Saida2");
    sc_trace(mVcdFile, Saida2_ap_vld, "(port)Saida2_ap_vld");
    sc_trace(mVcdFile, Entrada, "(port)Entrada");
#endif

    }
    mHdltvinHandle.open("CMF_duas_saidas.hdltvin.dat");
    mHdltvoutHandle.open("CMF_duas_saidas.hdltvout.dat");
}

CMF_duas_saidas::~CMF_duas_saidas() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void CMF_duas_saidas::thread_Saida1() {
    Saida1 = (!Entrada.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(Entrada.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void CMF_duas_saidas::thread_Saida1_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        Saida1_ap_vld = ap_const_logic_1;
    } else {
        Saida1_ap_vld = ap_const_logic_0;
    }
}

void CMF_duas_saidas::thread_Saida2() {
    Saida2 = (!Entrada.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<32>(): (sc_biguint<32>(Entrada.read()) + sc_biguint<32>(ap_const_lv32_2));
}

void CMF_duas_saidas::thread_Saida2_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        Saida2_ap_vld = ap_const_logic_1;
    } else {
        Saida2_ap_vld = ap_const_logic_0;
    }
}

void CMF_duas_saidas::thread_ap_done() {
    ap_done = ap_start.read();
}

void CMF_duas_saidas::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void CMF_duas_saidas::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void CMF_duas_saidas::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida1\" :  \"" << Saida1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida1_ap_vld\" :  \"" << Saida1_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida2\" :  \"" << Saida2.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida2_ap_vld\" :  \"" << Saida2_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Entrada\" :  \"" << Entrada.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

