// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CMF_duas_saidas,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.702000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=78,HLS_VERSION=2018_3}" *)

module CMF_duas_saidas (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Saida1,
        Saida1_ap_vld,
        Saida2,
        Saida2_ap_vld,
        Entrada
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] Saida1;
output   Saida1_ap_vld;
output  [31:0] Saida2;
output   Saida2_ap_vld;
input  [31:0] Entrada;

reg Saida1_ap_vld;
reg Saida2_ap_vld;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        Saida1_ap_vld = 1'b1;
    end else begin
        Saida1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        Saida2_ap_vld = 1'b1;
    end else begin
        Saida2_ap_vld = 1'b0;
    end
end

assign Saida1 = (Entrada + 32'd1);

assign Saida2 = (Entrada + 32'd2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

endmodule //CMF_duas_saidas
