-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CMFfixMult2 is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    EntradaA1_V : IN STD_LOGIC_VECTOR (17 downto 0);
    EntradaA2_V : IN STD_LOGIC_VECTOR (17 downto 0);
    SaidaA1_V : OUT STD_LOGIC_VECTOR (17 downto 0);
    SaidaA1_V_ap_vld : OUT STD_LOGIC;
    SaidaA2_V : OUT STD_LOGIC_VECTOR (17 downto 0);
    SaidaA2_V_ap_vld : OUT STD_LOGIC;
    SaidaB1_V : OUT STD_LOGIC_VECTOR (8 downto 0);
    SaidaB1_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of CMFfixMult2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "CMFfixMult2,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.180000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv9_161 : STD_LOGIC_VECTOR (8 downto 0) := "101100001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

    signal r_V_fu_83_p2 : STD_LOGIC_VECTOR (29 downto 0);

    component CMFfixMult2_mul_mbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;



begin
    CMFfixMult2_mul_mbkb_U1 : component CMFfixMult2_mul_mbkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => EntradaA2_V,
        din1 => EntradaA1_V,
        dout => r_V_fu_83_p2);




    SaidaA1_V <= r_V_fu_83_p2(29 downto 12);

    SaidaA1_V_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            SaidaA1_V_ap_vld <= ap_const_logic_1;
        else 
            SaidaA1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    SaidaA2_V <= r_V_fu_83_p2(29 downto 12);

    SaidaA2_V_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            SaidaA2_V_ap_vld <= ap_const_logic_1;
        else 
            SaidaA2_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    SaidaB1_V <= ap_const_lv9_161;

    SaidaB1_V_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            SaidaB1_V_ap_vld <= ap_const_logic_1;
        else 
            SaidaB1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
end behav;
