// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _CMFinterrupt2_HH_
#define _CMFinterrupt2_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct CMFinterrupt2 : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<1> > sinc;
    sc_out< sc_lv<16> > Saida1;
    sc_out< sc_logic > Saida1_ap_vld;
    sc_out< sc_lv<16> > Saida2;
    sc_out< sc_logic > Saida2_ap_vld;


    // Module declarations
    CMFinterrupt2(sc_module_name name);
    SC_HAS_PROCESS(CMFinterrupt2);

    ~CMFinterrupt2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > aux_sinc;
    sc_signal< sc_lv<16> > aux_saida2;
    sc_signal< sc_lv<16> > tmp_1_fu_76_p2;
    sc_signal< sc_lv<16> > ap_phi_mux_aux_saida2_loc_phi_fu_48_p4;
    sc_signal< sc_lv<1> > tmp_fu_59_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<16> ap_const_lv16_5;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Saida1();
    void thread_Saida1_ap_vld();
    void thread_Saida2();
    void thread_Saida2_ap_vld();
    void thread_ap_CS_fsm_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_aux_saida2_loc_phi_fu_48_p4();
    void thread_ap_ready();
    void thread_tmp_1_fu_76_p2();
    void thread_tmp_fu_59_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
