// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CMFinterrupt2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CMFinterrupt2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CMFinterrupt2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> CMFinterrupt2::ap_ST_fsm_state1 = "1";
const sc_lv<32> CMFinterrupt2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> CMFinterrupt2::ap_const_lv1_0 = "0";
const sc_lv<16> CMFinterrupt2::ap_const_lv16_1 = "1";
const sc_lv<1> CMFinterrupt2::ap_const_lv1_1 = "1";
const sc_lv<16> CMFinterrupt2::ap_const_lv16_5 = "101";
const bool CMFinterrupt2::ap_const_boolean_1 = true;

CMFinterrupt2::CMFinterrupt2(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Saida1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_Saida1_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_Saida2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_phi_mux_aux_saida2_loc_phi_fu_48_p4 );

    SC_METHOD(thread_Saida2_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_aux_saida2_loc_phi_fu_48_p4);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( aux_saida2 );
    sensitive << ( tmp_1_fu_76_p2 );
    sensitive << ( tmp_fu_59_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_1_fu_76_p2);
    sensitive << ( aux_saida2 );

    SC_METHOD(thread_tmp_fu_59_p2);
    sensitive << ( sinc );
    sensitive << ( aux_sinc );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    aux_sinc = "0";
    aux_saida2 = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CMFinterrupt2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sinc, "(port)sinc");
    sc_trace(mVcdFile, Saida1, "(port)Saida1");
    sc_trace(mVcdFile, Saida1_ap_vld, "(port)Saida1_ap_vld");
    sc_trace(mVcdFile, Saida2, "(port)Saida2");
    sc_trace(mVcdFile, Saida2_ap_vld, "(port)Saida2_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, aux_sinc, "aux_sinc");
    sc_trace(mVcdFile, aux_saida2, "aux_saida2");
    sc_trace(mVcdFile, tmp_1_fu_76_p2, "tmp_1_fu_76_p2");
    sc_trace(mVcdFile, ap_phi_mux_aux_saida2_loc_phi_fu_48_p4, "ap_phi_mux_aux_saida2_loc_phi_fu_48_p4");
    sc_trace(mVcdFile, tmp_fu_59_p2, "tmp_fu_59_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("CMFinterrupt2.hdltvin.dat");
    mHdltvoutHandle.open("CMFinterrupt2.hdltvout.dat");
}

CMFinterrupt2::~CMFinterrupt2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void CMFinterrupt2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_fu_59_p2.read(), ap_const_lv1_1))) {
        aux_saida2 = tmp_1_fu_76_p2.read();
        aux_sinc = sinc.read();
    }
}

void CMFinterrupt2::thread_Saida1() {
    Saida1 = ap_const_lv16_5;
}

void CMFinterrupt2::thread_Saida1_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        Saida1_ap_vld = ap_const_logic_1;
    } else {
        Saida1_ap_vld = ap_const_logic_0;
    }
}

void CMFinterrupt2::thread_Saida2() {
    Saida2 = ap_phi_mux_aux_saida2_loc_phi_fu_48_p4.read();
}

void CMFinterrupt2::thread_Saida2_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        Saida2_ap_vld = ap_const_logic_1;
    } else {
        Saida2_ap_vld = ap_const_logic_0;
    }
}

void CMFinterrupt2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CMFinterrupt2::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void CMFinterrupt2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CMFinterrupt2::thread_ap_phi_mux_aux_saida2_loc_phi_fu_48_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_59_p2.read())) {
            ap_phi_mux_aux_saida2_loc_phi_fu_48_p4 = aux_saida2.read();
        } else if (esl_seteq<1,1,1>(tmp_fu_59_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_aux_saida2_loc_phi_fu_48_p4 = tmp_1_fu_76_p2.read();
        } else {
            ap_phi_mux_aux_saida2_loc_phi_fu_48_p4 = "XXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_aux_saida2_loc_phi_fu_48_p4 = "XXXXXXXXXXXXXXXX";
    }
}

void CMFinterrupt2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void CMFinterrupt2::thread_tmp_1_fu_76_p2() {
    tmp_1_fu_76_p2 = (!aux_saida2.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(aux_saida2.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void CMFinterrupt2::thread_tmp_fu_59_p2() {
    tmp_fu_59_p2 = (aux_sinc.read() ^ sinc.read());
}

void CMFinterrupt2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm =  (sc_lv<1>) ("X");
            break;
    }
}

void CMFinterrupt2::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sinc\" :  \"" << sinc.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida1\" :  \"" << Saida1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida1_ap_vld\" :  \"" << Saida1_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida2\" :  \"" << Saida2.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Saida2_ap_vld\" :  \"" << Saida2_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

